peter50216/pwntools-ruby

- Gemfile.lock
- Rakefile
- lib/pwnlib/context.rb
- lib/pwnlib/dynelf.rb
- lib/pwnlib/ext/array.rb
- lib/pwnlib/ext/integer.rb
- lib/pwnlib/ext/string.rb
- lib/pwnlib/memleak.rb
- lib/pwnlib/pwn.rb
- lib/pwnlib/util/fiddling.rb
- lib/pwnlib/util/packing.rb
- pwntools.gemspec
- test/dynelf_test.rb
- test/memleak_test.rb
Also fix some whitespace / require order issue.
> Move from rainbow/os to pastel/tty-platform

- lib/pwnlib/constants/constants.rb
- lib/pwnlib/pwn.rb
- lib/pwnlib/util/cyclic.rb
- lib/pwnlib/util/fiddling.rb
- lib/pwnlib/util/packing.rb
- test/files/use_pwnlib.rb
- test/util/cyclic_test.rb
- test/util/fiddling_test.rb
- test/util/packing_test.rb
All other projects (rails, datamapper, httparty, happymapper) use
ClassMethods.
> ClassMethod -> ClassMethods

- .travis.yml
- travis/travis_fastfail.sh
* Only build master (This also builds PR)
* Only build latest PR change (to prevent piled up builds.)
> Speed up travis CI build

- Gemfile
- Gemfile.lock
- lib/pwnlib/constants/constants.rb
- test/constants/constants_test.rb
> use dentaku to implement safe Constants.eval

- .rubocop.yml
- Gemfile.lock
- Rakefile
- pwntools.gemspec
remove `task.formatters = ['files']` in Rakefile
also upgrade bundler :p
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/19)
> Upgrade rubocop and disable Style/Encoding

- .rubocop.yml
- .yardopts
- Rakefile
- STYLE.md
- lib/pwn.rb
- lib/pwnlib/constants/constant.rb
- lib/pwnlib/constants/constants.rb
- lib/pwnlib/context.rb
- lib/pwnlib/dynelf.rb
- lib/pwnlib/ext/helper.rb
- lib/pwnlib/memleak.rb
- lib/pwnlib/pwn.rb
- lib/pwnlib/reg_sort.rb
- lib/pwnlib/util/cyclic.rb
- lib/pwnlib/util/fiddling.rb
- lib/pwnlib/util/hexdump.rb
- lib/pwnlib/util/packing.rb
- lib/pwnlib/util/ruby.rb
- test/constants/constant_test.rb
- test/constants/constants_test.rb
- test/context_test.rb
- test/dynelf_test.rb
- test/ext_test.rb
- test/files/use_pwnlib.rb
- test/memleak_test.rb
- test/reg_sort_test.rb
- test/util/cyclic_test.rb
- test/util/fiddling_test.rb
- test/util/hexdump_test.rb
- test/util/packing_test.rb
Make docs style consistent.
Also add a tag `@diff` for difference with python-pwntools.
Also refactor MemLeak / DynELF and add docs for methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/22)
> Some document style fixes.

- .pullapprove.yml
Add hanhanW to reviewer for pullapprove.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/30)
> Add hanhanW to reviewer.

- .travis.yml
As title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/32)
> Specify travis distribution to trusty

- .travis.yml
fix as comment's suggestion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/52)
> Fix travis-ci/travis-ci#855 - brew broken on osx

- Gemfile.lock
- lib/pwnlib/version.rb
- pwntools.gemspec
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/55)
> bump 1.0.0

- lib/pwnlib/context.rb
- test/context_test.rb
* Support using +Symbol+ to updating the environment.
* Add the documentations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/57)
> Support using +Symbol+ to updating the environment.

- Gemfile.lock
- lib/pwnlib/version.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/64)
> bump 1.0.1

- lib/pwnlib/shellcraft/generators/amd64/linux/cat.rb
- lib/pwnlib/shellcraft/generators/i386/linux/cat.rb
- lib/pwnlib/shellcraft/generators/x86/linux/cat.rb
- test/shellcraft/linux/cat_test.rb
As title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/67)
> Implement shellcraft.cat

- travis/install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/82)
> Use xenial instead of zesty in travis/install.sh

- .rubocop.yml
- .travis.yml
- Gemfile.lock
- lib/pwnlib/context.rb
- lib/pwnlib/elf/elf.rb
- lib/pwnlib/ext/helper.rb
- lib/pwnlib/reg_sort.rb
- lib/pwnlib/tubes/tube.rb
- lib/pwnlib/util/packing.rb
- pwntools.gemspec
- test/files/use_pwn.rb
- test/test_helper.rb
- test/tubes/tube_test.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/83)
> Upgrade rubocop to 0.52.1 and remove codeclimate-test-reporter

- test/elf/elf_test.rb
- test/shellcraft/shellcraft_test.rb
- test/test_helper.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/84)
> Capture logger's output in test (issue #58)

- lib/pwnlib/asm.rb
- lib/pwnlib/errors.rb
- lib/pwnlib/shellcraft/shellcraft.rb
- test/asm_test.rb
- test/shellcraft/shellcraft_test.rb
Half part of #66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/88)
> Implement Asm.make_elf

- .rubocop.yml
- Gemfile.lock
- pwntools.gemspec
- test/tubes/tube_test.rb
#103 is broken
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/104)
> Bump rubocop

- travis/install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/109)
> Add apt update to fix Travis

- lib/pwnlib/timer.rb
- lib/pwnlib/tubes/sock.rb
- lib/pwnlib/tubes/tube.rb
- test/timer_test.rb
- test/tubes/sock_test.rb
- test/tubes/tube_test.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/116)
> Fixed #115 and refactor Tube#io

- Gemfile.lock
- README.md
- lib/pwnlib/version.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/122)
> Bump v1.1.0

- lib/pwnlib/ext/string.rb
- lib/pwnlib/util/fiddling.rb
- test/util/fiddling_test.rb
Closed #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/126)
> Implemented Fiddling.xor

- lib/pwnlib/asm.rb
- test/asm_test.rb
Closed #123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/125)
> Let created ELF has rwx segment

- lib/pwnlib/pwn.rb
- lib/pwnlib/runner.rb
- test/runner_test.rb
- test/tubes/process_test.rb
Closed #66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/124)
> Implemented module Runner

- travis/install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/135)
> Fix installation of capstone

- .codeclimate.yml
- lib/pwnlib/elf/elf.rb
- lib/pwnlib/errors.rb
- lib/pwnlib/shellcraft/generators/x86/linux/syscall.rb
- lib/pwnlib/timer.rb
- lib/pwnlib/util/hexdump.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/151)
> Slightly modify docs and address 4 codeclimate issues

- README.md
This fix #163 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/166)
> Add Rawsec's CyberSecurity Inventory badge

- lib/pwnlib/logger.rb
- test/logger_test.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/174)
> Cache the result of source_of (#172)

- lib/pwnlib/tubes/buffer.rb
- lib/pwnlib/tubes/tube.rb
- test/tubes/tube_test.rb
Closes #68
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/179)
> Implement Tubes#recvall

- lib/pwnlib/shellcraft/generators/i386/common/memcpy.rb
- lib/pwnlib/shellcraft/generators/x86/common/memcpy.rb
- lib/pwnlib/shellcraft/generators/x86/common/setregs.rb
- test/shellcraft/memcpy_test.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/183)
> Add shellcraft.memcpy for x86

- lib/pwnlib/shellcraft/generators/amd64/linux/sleep.rb
- lib/pwnlib/shellcraft/generators/i386/linux/sleep.rb
- lib/pwnlib/shellcraft/generators/x86/linux/sleep.rb
- tasks/shellcraft/x86.rake
- test/shellcraft/linux/sleep_test.rb
closes #181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/184)
> Implement shellcraft.sleep

- lib/pwnlib/logger.rb
- test/full_file_test.rb
close #193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/199)
> Fix error when required from Ruby CLI

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/207)
> Drop Ruby 2.3 and add 2.6 to travis.yml

- .travis.yml
- travis/install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/224)
> Trusty -> Xenial in .travis.yml

- Gemfile.lock
- lib/pwnlib/version.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/226)
> Bump version 1.2.0

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/230)
> Drop Ruby 2.3 in Appveyor

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/232)
> Update links to Rawsec's inventory

- Gemfile.lock
- pwntools.gemspec
Fix #227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/231)
> Update dependency of method_source to >= 0.9

- .github/workflows/ruby.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/243)
> Send coverage report to codeclimate

- test/tubes/process_test.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/244)
> Fix flaky EOF test in process_test

- Gemfile.lock
- lib/pwnlib/version.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/251)
> Bump version 1.2.1

- .github/workflows/ruby.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/peter50216/pwntools-ruby/264)
> Don't attempt to send coverage report for external PRs
